[2022-10-10 16:23:22,851] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table __airflow_temporary_run_2022-10-10T16:23:15.380166+00:00__ [queued]>
[2022-10-10 16:23:22,951] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table __airflow_temporary_run_2022-10-10T16:23:15.380166+00:00__ [queued]>
[2022-10-10 16:23:22,956] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-10 16:23:22,958] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-10 16:23:22,960] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-10 16:23:23,043] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-01-01 00:00:00+00:00
[2022-10-10 16:23:23,123] {standard_task_runner.py:52} INFO - Started process 6440 to run task
[2022-10-10 16:23:23,253] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', '__***_temporary_run_2022-10-10T16:23:15.380166+00:00__', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp0s7oa54b', '--error-file', '/tmp/tmpad8cbvpy']
[2022-10-10 16:23:23,256] {standard_task_runner.py:80} INFO - Job 16: Subtask create_table
[2022-10-10 16:23:24,504] {task_command.py:369} INFO - Running <TaskInstance: user_processing.create_table __airflow_temporary_run_2022-10-10T16:23:15.380166+00:00__ [running]> on host 09023156d4e0
[2022-10-10 16:23:31,923] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=__***_temporary_run_2022-10-10T16:23:15.380166+00:00__
[2022-10-10 16:23:33,070] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-10-10 16:23:33,141] {dbapi.py:208} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                usernmae TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        , parameters: None
[2022-10-10 16:23:33,176] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2022-10-10 16:23:35,321] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20220101T000000, start_date=20221010T162322, end_date=20221010T162335
[2022-10-10 16:23:36,716] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-10 16:23:37,112] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
